const THREE_DAYS_IN_MILLISECONDS = 1000 * 60 * 60 * 24 * 3;
const TWENTYFOUR_HOURS_IN_MILLISECONDS = 1000 * 60 * 60 * 24;
const THREE_HOURS_IN_MILLISECONDS = 1000 * 60 * 60 * 3;
const FIFTEEN_MINUTES_IN_MILLISECONDS = 1000 * 60 * 15;
const TEN_MINUTES_IN_MILLISECONDS = 1000 * 60 * 10;
const FIVE_MINUTES_IN_MILLISECONDS = 1000 * 60 * 5;
const THREE_MINUTES_IN_MILLISECONDS= 1000 * 60 * 3;
const ONE_MINUTE_IN_MILLISECONDS = 1000 * 60 * 1;
const FIVE_SECONDS_IN_MILLISECONDS = 1000 * 5;
const ONE_SECOND_IN_MILLISECONDS = 1000;
const SESSION_NAME = 'loginUserSession';
const SESSION_SECRET = 'longsecretstringtopreventfromguessingthesessions';
const IDLE_SESSION_COUNTDOWN_VALUE = 'idleSessionCountdownValue';
const LOGOUT_SESSION_COUNTDOWN_VALUE = 'logoutSessionCountdownValue';
const SESSION_EXPIRATION_TIME_IN_MILLISECONDS = TWENTYFOUR_HOURS_IN_MILLISECONDS;
const SESSION_UPDATE_FREQUENCY_IN_MILLISECONDS = THREE_MINUTES_IN_MILLISECONDS;
const EXPIRED_SESSION_CLEANUP_FREQUENCY_IN_MILLISECONDS = THREE_MINUTES_IN_MILLISECONDS;
const IDLE_SESSION_COUNTDOWN_SIXTY_SECONDS_IN_MILLISECONDS = ONE_MINUTE_IN_MILLISECONDS;

const SessionConfig = Object.freeze({
    SESSION_NAME : SESSION_NAME,
    ONE_SECOND_IN_MILLISECONDS:ONE_SECOND_IN_MILLISECONDS,
    ONE_MINUTE_IN_MILLISECONDS:ONE_MINUTE_IN_MILLISECONDS,
    SESSION_EXPIRATION_TIME_IN_MILLISECONDS : SESSION_EXPIRATION_TIME_IN_MILLISECONDS,
    SESSION_UPDATE_FREQUENCY_IN_MILLISECONDS : SESSION_UPDATE_FREQUENCY_IN_MILLISECONDS,
    SESSION_DEFAULT_DELAYS_IN_NOTIFICATIONS: FIVE_SECONDS_IN_MILLISECONDS,
    EXPIRED_SESSION_CLEANUP_FREQUENCY_IN_MILLISECONDS : EXPIRED_SESSION_CLEANUP_FREQUENCY_IN_MILLISECONDS,
    IDLE_SESSION_COUNTDOWN_SIXTY_SECONDS_IN_MILLISECONDS : IDLE_SESSION_COUNTDOWN_SIXTY_SECONDS_IN_MILLISECONDS,
    IDLE_SESSION_COUNTDOWN_VALUE : IDLE_SESSION_COUNTDOWN_VALUE,
    LOGOUT_SESSION_COUNTDOWN_VALUE : LOGOUT_SESSION_COUNTDOWN_VALUE
});


export default SessionConfig;